services:
#clickhouse
- type: pserv
    name: clickhouse
    env: docker
    plan: standard
    autoDeploy: false
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 10
    envVars:
      - key: ALLOW_EMPTY_PASSWORD
        value: yes
      - key: CLICKHOUSE_TCP_PORT
        value: 9000
      - key: CLICKHOUSE_HTTP_PORT
        value: 8123
    startCommand: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
#server
- type: pserv
    name: clickhouse
    env: docker
    dockerfile: 
    plan: standard
    autoDeploy: false
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 10
      
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 8000:8000
    depends_on:
      - clickhouse
    networks:
      - net

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml
    networks:
      - net

volumes:
  clickhouse_data:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local
